/****
This SQL script was generated by the Configure Data Synchronization
dialog box. This script contains statements that create the
change-tracking columns, deleted-items table, and triggers on the
server database. These database objects are required by Synchronization
Services to successfully synchronize data between client and server
databases. For more information, see the
‘How to: Configure a Database Server for Synchronization’ topic in Help.
****/


IF @@TRANCOUNT > 0
set ANSI_NULLS ON 
set QUOTED_IDENTIFIER ON 

GO
BEGIN TRANSACTION;


IF @@TRANCOUNT > 0
ALTER TABLE [dbo].[Quote] 
ADD [CreationDate] DateTime NULL CONSTRAINT [DF_Quote_CreationDate] DEFAULT (GETUTCDATE()) WITH VALUES
GO
IF @@ERROR <> 0 
     ROLLBACK TRANSACTION;


IF @@TRANCOUNT > 0
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[dbo].[Quote_InsertTrigger]') AND type = 'TR') 
   DROP TRIGGER [dbo].[Quote_InsertTrigger] 

GO
CREATE TRIGGER [dbo].[Quote_InsertTrigger] 
    ON [dbo].[Quote] 
    AFTER INSERT 
AS 
BEGIN 
    SET NOCOUNT ON 
    UPDATE [dbo].[Quote] 
    SET [CreationDate] = GETUTCDATE() 
    FROM inserted 
    WHERE inserted.[Quote_ID] = [dbo].[Quote].[Quote_ID] 
END;
GO
IF @@ERROR <> 0 
     ROLLBACK TRANSACTION;
COMMIT TRANSACTION;
